services:
  splayer-web:
    image: ${DOCKER_IMAGE:-wudiming/dmsplayerwebx:latest}
    # build:
    #   context: ..
    #   dockerfile: docker/Dockerfile
    container_name: splayer-web
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      - PORT=5173
      - TZ=Asia/Shanghai
      # - NETEASE_ENHANCED_URL=http://your-ncm-api:3000
